trash_collector_proj/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector_proj/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('employee_form/', views.employee_form, name='employee_form'),
    path('create_employee_profile/', views.create_employee_profile, name='create_employee_profile'),
    path('employee_profile/<int:employee_id>/', views.employee_profile, name='employee_profile'),
    path('employee_prospects/<int:employee_id>', views.employee_prospects, name='employee_prospects'),
    path('employee_prospect_search/<int:employee_id>/', views.prospect_search, name='prospect_search'),
    path('employee_prospect/results/<str:form_input>/<int:employee_id>/', views.employee_prospect_results, name='employee_prospect_results'),
    path('confirm_pickup/one_time/<int:employee_id>/<int:customer_id>/', views.confirm_one_time, name='confirm_one_time'),
    path('confirm_pickup/weekly/<int:employee_id>/<int:customer_id>/', views.confirm_weekly, name='confirm_weekly')
]

trash_collector_proj/employees/models.py
from django.db import models


# Create your models here.

# TODO: Create an Employee model with properties required by the user stories

class Employee(models.Model):
    name = models.CharField(max_length=50)
    route_zipcode = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

trash_collector_proj/employees/views.py
import random

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, reverse
from django.apps import apps
from .models import Employee
from datetime import date

# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.


def index(request):
    # Get the Customer model from the other app, it can now be used to query the db
    Customer = apps.get_model('customers.Customer')
    user = request.user
    print(user)
    all_employees = Employee.objects.all()
    for employee in all_employees:
        if user.id == employee.user_id:
            return HttpResponseRedirect(f'/employees/employee_profile/{employee.id}')
    return HttpResponseRedirect(reverse('employees:employee_form'))


def employee_form(request):
    return render(request, 'employees/employee.html')


def create_employee_profile(request):
    user = request.user
    if request.method == 'POST':
        name = request.POST.get('name')
        zip_code = request.POST.get('zip_code')
        user_id = user
        new_employee = Employee(name=name, route_zipcode=zip_code, user=user_id)
        new_employee.save()
        return HttpResponseRedirect(f'/employees/employee_profile/{new_employee.id}')
    else:
        return HttpResponseRedirect('/employees/employee_form')


def employee_profile(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    customers = apps.get_model('customers.Customer')
    all_customers = customers.objects.all()
    today = date.today()
    day = date.today().strftime("%A")
    context = {
        'employee': employee,
        'customers': all_customers,
        'date': today,
        'day': day
    }
    return render(request, 'employees/employee_profile.html', context)


def employee_prospects(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    customer = apps.get_model('customers.Customer')
    all_customers = customer.objects.all()
    context = {
        'employee': employee,
        'customers': all_customers
    }
    return render(request, 'employees/employee_prospects.html', context)


def prospect_search(request, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    if request.method == 'POST':
        form_input = request.POST.get('pickup_day')
        return HttpResponseRedirect(f'/employees/employee_prospect/results/{form_input}/{employee.id}')


def employee_prospect_results(request, form_input, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    Customer = apps.get_model('customers.Customer')
    customers = Customer.objects.all()
    pickup_day = form_input
    prospects = Customer.objects.filter(weekly_pickup=pickup_day)
    context = {
        'employee': employee,
        'customers': customers,
        'prospects': prospects
    }
    print(pickup_day)
    print(customers)
    return render(request, 'employees/employee_prospect_results.html', context)


def confirm_one_time(request, customer_id, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    Customer = apps.get_model('customers.Customer')
    target_customer = Customer.objects.get(pk=customer_id)
    target_customer.one_time_pickup = None
    target_customer.balance += 10
    target_customer.save()
    return redirect(f'/employees/employee_profile/{employee.id}')


def confirm_weekly(request, customer_id, employee_id):
    employee = Employee.objects.get(pk=employee_id)
    Customer = apps.get_model('customers.Customer')
    target_customer = Customer.objects.get(pk=customer_id)
    target_customer.weekly_pickup = None
    target_customer.balance += 10
    target_customer.save()
    return redirect(f'/employees/employee_profile/{employee.id}')

trash_collector_proj/employees/templates/employees/employee.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/employee.css' %}">
{% endblock %}

{% block content %}
<div class="employee-form" id="employee-form">
    <div class="employee-border">
        <h1 class="text-center my-5">Create Your Employee Account</h1>
        <hr class="hr-form">
        <div class="right-display-one my-5">
              <h3>Employee Info</h3>
        </div>
        <div class="left-change-one">
            <form action="{% url 'employees:create_employee_profile' %}" method="post">
                {% csrf_token %}
                <div class="form-group center">
                    name:<input class="form-control form-control-sm col-sm-4" type="text" name="name" id="name"><br>
                    zipcode:<input class="form-control form-control-sm col-sm-4" type="text" name="zip_code" id="zip_code"><br>
                </div>
                <input type="submit" value="sign up">
            </form>
        </div>
    </div>
</div>
<!--<form action="{% url 'employees:create_employee_profile' %}" method="post">
    {% csrf_token %}
    name: <input type="text" id="name" name="name">
    zip code: <input type="text" id="zip_code" name="zip_code">
    <input type="submit" value="submit">
</form>-->
{% endblock %}

trash_collector_proj/employees/templates/employees/employee_profile.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/employee_profile.css' %}">
{% endblock %}

{% block anchors_employee %}
    <li><a href="{% url 'employees:employee_profile' employee.id %}">Daily View</a></li>
    <li><a href="{% url 'employees:employee_prospects' employee.id %}">Prospects</a></li>
    <li><a href="{% url 'logout' %}">Log Out</a></li>
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="employee-info text-center" id="employee_info">
            <h1><b>Employee -</b> {{employee.name}}</h1>
            <hr>
            <h2>{{day}} {{date}}</h2>
            <h3 class="my-4"><b>Assigned Zip Code:</b> {{employee.route_zipcode}}</h3>
        </div>
    <div class="display my-5">
        <div class="pickups-today">
            <h3>Customer Pickups Today</h3>
            <hr>
            <table class="table">
                <thead>
                    <tr>
                        <th class="thead col-2">Name</th>
                        <th class="thead col-2">One Time Pickup</th>
                        <th class="thead col-2">Daily Pickup</th>
                        <th class="thead col-2 ">Location</th>
                        <th class="thead col-2">Zip Code</th>
                        <th class="thead col-2">Confirm Pickup</th>
                    </tr>
                </thead>
                {% for customer in customers %}
        {% if customer.one_time_pickup == date %} %}
                <tr>
                    <td>{{customer.name}}</td>
                    <td>{{customer.one_time_pickup}}</td>
                    <td>Slot</td>
                    <td>{{customer.address}}</td>
                    <td>{{customer.zipcode}}</td>
                    <td><a class="btn btn-sm btn-primary" href="/employees/confirm_pickup/one_time/{{employee.id}}/{{customer.id}}">Confirm Pickup</a></td>
                </tr>
            <!--<p>{{customer.name}} - {{customer.one_time_pickup}} <a class="btn btn-sm btn-success" href="/employees/confirm_pickup/one_time/{{employee.id}}/{{customer.id}}">Confirm Pickup</a></p>-->
        {% elif customer.weekly_pickup == day %}
                <tr>
                    <td>{{customer.name}}</td>
                    <td>Slot</td>
                    <td>{{customer.weekly_pickup}}</td>
                    <td>{{customer.address}}</td>
                    <td>{{customer.zipcode}}</td>
                    <td><a class="btn btn-sm btn-primary" href="/employees/confirm_pickup/weekly/{{employee.id}}/{{customer.id}}">Confirm Pickup</a></td>
                </tr>
            <!--<p>{{customer.name}} - {{customer.weekly_pickup}} <a class="btn btn-sm btn-success" href="/employees/confirm_pickup/weekly/{{employee.id}}/{{customer.id}}">Confirm Pickup</a></p>-->
        {% endif %}
    {% endfor %}
            </table>
        </div>
        <div class="nearby-customers">
            <h3>Customers in my area:</h3>
            <hr>
            <table class="table table-bordered" id="table">
                <thead class="thead-dark">
                    <tr>
                        <th class="thead">Name</th>
                        <th class="thead">Location</th>
                        <th class="thead">Zip Code</th>
                    </tr>
                </thead>
                {% for customer in customers %}
                {% if employee.route_zipcode == customer.zipcode and customer.start_date is not None %}
                    <tr>
                        <td>{{customer.name}}</td>
                        <td>{{customer.address}}</td>
                        <td>{{customer.zipcode}}</td>
                    </tr>
                {% endif %}
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

trash_collector_proj/employees/templates/employees/employee_prospect_results.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/employee_prospects_results.css' %}">
{% endblock %}

{% block anchors_employee %}
    <li><a href="{% url 'employees:employee_profile' employee.id %}">Daily View</a></li>
    <li><a href="{% url 'employees:employee_prospects' employee.id %}">Prospects</a></li>
{% endblock %}

{% block header %}
<h1>{{employee.name}}</h1>
{% endblock %}

{% block content %}
<div class="container-fluid">
<div class="results">
    <h1>Prospect Results</h1>
    <table class="table table-striped my-5">
        <thead>
            <tr>
                <th class="col-3">Name</th>
                <th class="col-3">Location</th>
                <th class="col-3">Zip Code</th>
                <th class="col-3">Weekly Pickup Day</th>
            </tr>
        </thead>
        {% for prospect in prospects %}
        {% if prospect.zipcode == employee.route_zipcode %}
        <tr>
            <td>{{prospect.name}}</td>
            <td>{{prospect.address}}</td>
            <td>{{prospect.zipcode}}</td>
            <td>{{prospect.weekly_pickup}}</td>
        </tr>
        {% endif %}
    {% endfor %}
    </table>
</div>
</div>
{% endblock %}

trash_collector_proj/employees/templates/employees/employee_prospects.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/employee_prospects.css' %}">
{% endblock %}

{% block anchors_employee %}
    <li><a href="{% url 'employees:employee_profile' employee.id %}">Daily View</a></li>
    <li><a href="">Prospects</a></li>
{% endblock %}

{% block content %}
<div class="prospect-form" id="prospect-form">
    <div class="form-border">
        <h1 class="text-center">Prospects By Day</h1>
        <hr class="hr-form">
        <div class="right-display-change my-5">
          <h3><b>Employee Name:</b> {{employee.name}}</h3>
          <p class="zipcode"><b>Zip Code:</b> {{employee.route_zipcode}}</p>
        </div>
        <div class="left-side-change">
            <form action="{% url 'employees:prospect_search' employee.id%}" method="post">
            {% csrf_token %}
                <div class="form-group">
                    <p id="change-day-message" class="text-center">Upcoming Pickups in Your Zip Code</p>
                    <div class="d-flex flex-row">
                        <select name="pickup_day" class="form-control">
                            <option value="Monday">Monday</option>
                            <option value="Tuesday">Tuesday</option>
                            <option value="Wednesday">Wednesday</option>
                            <option value="Thursday">Thursday</option>
                            <option value="Friday">Friday</option>
                            <option value="Saturday">Saturday</option>
                        </select>
                        <input class="btn btn-sm btn-success mx-2" id="change-day" type="submit" value="Search">
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

trash_collector_proj/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Employee {{ user.username }}!
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}