trash_collector_proj/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector_proj/customers/urls.py
from django.urls import path
from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('customer_form/', views.customer_form, name='customer_form'),
    path('create_profile/', views.create, name='create'),
    path('customer_profile/<int:customer_id>/', views.customer_profile, name='customer_profile'),
    path('customer_profile/change_pickup/<int:customer_id>', views.change_pickup, name='change_pickup'),
    path('update_weekly_pickup/<int:customer_id>', views.update_weekly_pickup, name='update_weekly_pickup'),
    path('one_time_pickup/<int:customer_id>', views.one_time_pickup, name='one_time_pickup'),
    path('account_period/<int:customer_id>', views.account_period, name='account_period'),
    path('suspend_account/<int:customer_id>', views.suspend_account, name='suspend_account')
]

trash_collector_proj/customers/models.py
from django.db import models


# Create your models here.

# TODO: Finish customer model by adding necessary properties to fulfill user stories


class Customer(models.Model):
    name = models.CharField(max_length=50)
    weekly_pickup = models.CharField(max_length=50, null=True)
    one_time_pickup = models.DateField(null=True, blank=True)
    balance = models.IntegerField()
    start_date = models.DateField(null=True)
    end_date = models.DateField(null=True)
    address = models.CharField(max_length=50)
    zipcode = models.CharField(max_length=50)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

trash_collector_proj/customers/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Customer


# TODO: Create a function for each path created in customers/urls.py. Each will need a template as well.


def index(request):
    # The following line will get the logged-in in user (if there is one) within any view function
    user = request.user
    # It will be necessary while creating a customer/employee to assign the logged-in user as the user foreign key
    # This will allow you to later query the database using the logged-in user,
    # thereby finding the customer/employee profile that matches with the logged-in user.
    print(user)
    customers = Customer.objects.all()
    for customer in customers:
        if user.id == customer.user.id:
            print(f'This user has a customer account')
            print(f'customer ID is {customer.id}')
            return HttpResponseRedirect(f'customer_profile/{customer.id}')
        else:
            print('This user has no customer profile')
    return HttpResponseRedirect(reverse('customers:customer_form'))


def customer_form(request):
    return render(request, 'customers/customer.html')


def create(request):
    user_id = request.user
    print(user_id.id)
    if request.method == 'POST':
        name = request.POST.get('name')
        address = request.POST.get('address')
        zip_code = request.POST.get('zipcode')
        user_id = user_id
        new_customer = Customer(name=name, address=address,
                                zipcode=zip_code, balance=0, user=user_id)
        new_customer.save()
        return HttpResponseRedirect(f'/customers/customer_profile/{new_customer.id}')
    else:
        return render(request, '/customer.html')


def customer_profile(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    context = {
        'customer': customer,
    }
    return render(request, 'customers/customer_profile.html', context)


def change_pickup(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    context = {
        'customer': customer
    }
    return render(request, 'customers/change_pickup.html', context)


def update_weekly_pickup(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    change_weekly_pickup = request.POST.get('update_weekly_pickup')
    customer.weekly_pickup = change_weekly_pickup
    customer.save()
    # include '/' before redirect
    return HttpResponseRedirect(f'/customers/customer_profile/{customer.id}')


def one_time_pickup(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    customer.one_time_pickup = request.POST.get('one_time_pickup')
    customer.save()
    return HttpResponseRedirect(f'/customers/customer_profile/{customer.id}')


def account_period(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    customer.start_date = request.POST.get('start_date')
    customer.end_date = request.POST.get('end_date')
    customer.save()
    return HttpResponseRedirect(f'/customers/customer_profile/{customer.id}')


def suspend_account(request, customer_id):
    customer = Customer.objects.get(pk=customer_id)
    customer.start_date = None
    customer.end_date = None
    customer.weekly_pickup = None
    customer.one_time_pickup = None
    customer.save()
    return HttpResponseRedirect(f'/customers/customer_profile/{customer.id}')

trash_collector_proj/customers/templates/customers/change_pickup.html
{% extends 'base.html'  %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/change_pickup.css' %}">
{% endblock %}

{% block title %} {{customer.name}} | Change Pickup {% endblock %}

{% block anchors %}
<li><a href="{% url 'customers:customer_profile' customer.id %}">Account Info</a></li>
    <li><a href="{% url 'customers:change_pickup' customer.id %}">Change Pick-up Day</a></li>
    <li><a href="{% url 'customers:suspend_account' customer.id %}">Suspend Account</a></li>
{% endblock %}

{% block header %}
{% endblock %}

{% block content %}
<div class="change-forms">
    <div class="change-weekly">
        <form action="{% url 'customers:update_weekly_pickup' customer.id %}" method="post">
        {% csrf_token %}
            <div class="form-group">
                <p id="schedule-message" class="text-center">Update your weekly service day</p>
                <div class="d-flex flex-row">
                    <select id="update_weekly_pickup" name="update_weekly_pickup" class="form-control">
                        <option value="Monday">Monday</option>
                        <option value="Tuesday">Tuesday</option>
                        <option value="Wednesday">Wednesday</option>
                        <option value="Thursday">Thursday</option>
                        <option value="Friday">Friday</option>
                        <option value="Saturday">Saturday</option>
                    </select>
                    <input class="btn btn-sm btn-primary mx-2" id="schedule-day" type="submit" value="schedule">
                </div>
            </div>
        </form>
    </div>
    <div class="change-one-time">
        <form action="{% url 'customers:one_time_pickup' customer.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="one_time_pickup">update one time pickup</label>
                <input class="form-control col-10" type="date" id="one_time_pickup" name="one_time_pickup">
                <br>
                <input id="confirm-one-time" type="submit" value="confirm">
            </div>
        </form>
    </div>
</div>

{% endblock %}

trash_collector_proj/customers/templates/customers/customer.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/customer.css' %}">
{% endblock %}

{% block content %}
<div class="customer-form" id="customer-form">
    <div class="customer-border">
        <h1 class="text-center my-5">Create Your Customer Account</h1>
        <hr class="hr-form">
        <div class="right-display-one my-5">
              <h3>Customer Info</h3>
        </div>
        <div class="left-change-one">
            <form action="{% url 'customers:create' %}" method="post">
                {% csrf_token %}
                <div class="form-group center">
                    name:<input class="form-control form-control-sm col-sm-4" type="text" name="name" id="name"><br>
                    address:<input class="form-control form-control-sm col-sm-4" type="text" name="address" id="address"><br>
                    zipcode:<input class="form-control form-control-sm col-sm-4" type="text" name="zipcode" id="zipcode"><br>
                </div>
                <input type="submit" value="sign up">
            </form>
        </div>
    </div>
</div>
<!--<form action="{% url 'customers:create' %}" method="post">
    {% csrf_token %}
    <div class="form-group center">
        name:<input class="form-control form-control-sm col-sm-4" type="text" name="name" id="name"><br>
        address:<input class="form-control form-control-sm col-sm-4" type="text" name="address" id="address"><br>
        zipcode:<input class="form-control form-control-sm col-sm-4" type="text" name="zipcode" id="zipcode"><br>
    </div>
    <input type="submit" value="sign up">
</form>-->
{% endblock %}

trash_collector_proj/customers/templates/customers/customer_profile.html
{% extends 'base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '/css/customer_profile.css' %}">
{% endblock %}

{% block title %} {{customer.name}} | Trash_collector {% endblock %}

{% block anchors %}
<li><a href="{% url 'customers:customer_profile' customer.id %}">Account Info</a></li>
{% if customer.weekly_pickup != None %}
<li><a href="#change-day-form">Change Weekly Pickup</a></li>
{% endif %}
{% if customer.one_time_pickup != None %}
<li><a href="#one-time-form">Change One-Time Pickup</a></li>
{% endif %}
<li><a href="{% url 'customers:suspend_account' customer.id %}">Suspend Account</a></li>
<li><a href="{% url 'logout' %}">Log Out</a></li>
{% endblock %}

{% block header %}
<div class="text-center my-5">
    <h1>Welcome {{customer.name}}</h1>
</div>
    {% if customer.start_date == None or customer.end_date == None %}
    <p id="message">YOU WILL NEED A START AND END DATE IN ORDER TO SCHEDULE YOUR WEEKLY TRASH PICKUPS</p>
    {% elif customer.start_date != None and customer.end_date != None %}
    <p id="transparent">transparent</p>
    {% endif %}
{% endblock %}

{% block content %}
<div class="container-fluid">
    <div class="viewport">
    <div class="display my-2">
        <div class="left-side">
            <div class="balance">
                <h3>BALANCE: ${{customer.balance}}</h3>
            </div>
            <div class="weekly_pickup">
                <h3>WEEKLY PICKUP: {{customer.weekly_pickup}}</h3>
            </div>
        </div>
        <div class="right-side">
            {% if customer.start_date == None or customer.end_date == None %}
            <form action="{% url 'customers:account_period' customer.id %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <div class="start_end_date">
                        <div class="start_date">
                            <label for="start_date" class="mx-3">START DATE:</label>
                            <input class="form-control col-5" type="date" id="start_date" name="start_date">
                        </div>
                        <hr>
                        <div class="end_date">
                            <label for="end_date" class="mx-3">END DATE:</label>
                            <input class="form-control col-5" type="date" id="end_date" name="end_date">
                        </div>
                    </div>
                </div>
                <br>
                <div class="confirm">
                    <input id="confirm" type="submit" value="CONFIRM">
                </div>
            </form>
        </div>
        {% elif customer.start_date != None and customer.end_date != None %}
        <div class="right-side-display">
            <div class="start_date_display">
                <h3 id="display_start_date">START DATE: {{customer.start_date}}</h3>
            </div>
            <hr>
            <div class="end_date_display">
                <h3 id="display_end_date">END DATE: {{customer.end_date}}</h3>
            </div>
        </div>
    </div>
    </div>
        {% endif %}
    <div class="display-bottom">
        {% if customer.start_date != None and customer.end_date != None and customer.weekly_pickup == None %}
        <div class="weekly-pickup">
            <form action="{% url 'customers:update_weekly_pickup' customer.id %}" method="post">
            {% csrf_token %}
                <div class="form-group">
                    <p id="schedule-message" class="text-center">Schedule a weekly pick up day to start your service</p>
                    <div class="d-flex flex-row">
                        <select id="update_weekly_pickup" name="update_weekly_pickup" class="form-control">
                            <option value="Monday">Monday</option>
                            <option value="Tuesday">Tuesday</option>
                            <option value="Wednesday">Wednesday</option>
                            <option value="Thursday">Thursday</option>
                            <option value="Friday">Friday</option>
                            <option value="Saturday">Saturday</option>
                        </select>
                        <input class="btn btn-sm btn-primary mx-2" id="schedule-day" type="submit" value="schedule">
                    </div>
                </div>
            </form>
        </div>
        {% endif %}
        {% if customer.start_date != None and customer.end_date != None and customer.weekly_pickup != None and customer.one_time_pickup == None%}
        <div class="one-time-request">
            <form action="{% url 'customers:one_time_pickup' customer.id %}" method="post">
                {% csrf_token %}
                <div class="form-group d-flex flex-row one-time-group">
                    <p id="label-one-time">Would you like an extra one time pickup?</p>
                    <input class="form-control col-5" type="date" id="one_time_pickup" name="one_time_pickup">
                    <input id="confirm-one-time" type="submit" value="confirm">
                </div>
            </form>
        </div>
        {% elif customer.one_time_pickup != None %}
        <div class="one-time">
            <h3>Your one time pickup is scheduled on: {{customer.one_time_pickup}}</h3>
        </div>
        {% endif %}
    </div>
    </div>
{% if customer.weekly_pickup != None %}
    <div class="change-day-form" id="change-day-form">
        <div class="form-border">
            <h1 class="text-center">Change weekly pickup day</h1>
            <hr class="hr-form">
              <div class="right-display-change my-5">
                  <h2><b>Customer Name:</b> {{customer.name}}</h2>
                  <p class="my-4"><b>Address:</b> {{customer.address}}</p>
                  <p><b>Zip Code:</b> {{customer.zipcode}}</p>
                  <p><b>Current Weekly Pickup Day:</b> {{customer.weekly_pickup}}</p>
                </div>
                <div class="left-side-change">
                    <form action="{% url 'customers:update_weekly_pickup' customer.id %}" method="post">
                    {% csrf_token %}
                        <div class="form-group">
                            <p id="change-day-message" class="text-center">Choose a day most convenient for you!</p>
                            <div class="d-flex flex-row">
                                <select name="update_weekly_pickup" class="form-control">
                                    <option value="Monday">Monday</option>
                                    <option value="Tuesday">Tuesday</option>
                                    <option value="Wednesday">Wednesday</option>
                                    <option value="Thursday">Thursday</option>
                                    <option value="Friday">Friday</option>
                                    <option value="Saturday">Saturday</option>
                                </select>
                                <input class="btn btn-sm btn-primary mx-2" id="change-day" type="submit" value="schedule">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    <div class="one-time-form" id="one-time-form">
        <div class="one-time-border">
            <h1 class="text-center">Change One Time Pickup Day</h1>
            <hr class="hr-form">
            <div class="right-display-one my-5">
                  <h2><b>Customer Name:</b> {{customer.name}}</h2>
                  <p class="my-4"><b>Address:</b> {{customer.address}}</p>
                  <p><b>Zip Code:</b> {{customer.zipcode}}</p>
                  <p><b>Current One-Time Pickup Day:</b> {{customer.one_time_pickup}}</p>
            </div>
            <div class="left-change-one">
                <form action="{% url 'customers:one_time_pickup' customer.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="one-time-group">
                            <label for="one_time_pickup" id="change-one-time-message">Would you like an extra one time pickup?</label>
                            <input class="form-control col-5 one-time-input my-3" type="date" name="one_time_pickup">
                            <div class="input-one-time">
                                <input id="confirm-change-one-time" type="submit" value="confirm" class="btn btn-sm btn-success my-4">
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endif %}
</div>
{% endblock %}

trash_collector_proj/customers/templates/customers/index.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Customer Home {% endblock %}

{% block header %} Customer Home {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    Hello Customer {{ user.username }}!
  {% else %}
    <p>You are at the customer index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}